server:
  eliteLogDir:  '%userprofile%/Saved Games/Frontier Developments/Elite Dangerous'
  
client:
  guiScale:     1.0
  compact:      true
  themeColor:   '#ff7b00' # orange: #ff7b00 / blue: #02a5ec / emerald: #00ffaa
  fullColor:    false
  shadow:       true
